name: call-build-test-reusable

on: push

jobs:
  call-reusable-workflow:
    # Importing a reusable workflow from another repository and branch
    uses: msnellma/actions-learning-pathway/.github/workflows/build-test-reusable.yaml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
